spring:
  profiles:
    active: dev
---


spring:
  profiles: dev
  application:
    name: dev-cloud
server:
  port: 8001
---
spring:
  profiles: test
  application:
    name: test-cloud
server:
  port: 8002